---
- name: Configure mgmt servers
  hosts: mgmt_servers
  become: true

  tasks:
    - name: Include Pi-Hole role
      ansible.builtin.include_role:
        name: kpsinghchouhan.linux_management_roles.pi_hole
