---
- name: Configure management server
  hosts: mgmt-server
  become: true

  pre_tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['distribution'] == 'Ubuntu'

  tasks:
    - name: Include PostgreSQL role
      ansible.builtin.include_role:
        name: kpsinghchouhan.linux_platform_roles.postgresql

    - name: Include PowerDNS role
      ansible.builtin.include_role:
        name: kpsinghchouhan.linux_management_roles.powerdns
