---
all:
  hosts:
    mgmt-server:
      ansible_host: 192.168.153.129
      ansible_port: 2211
    jumpbox:
      ansible_host: 192.168.153.129
      ansible_port: 2212
    haproxy:
      ansible_host: 192.168.153.129
      ansible_port: 2213
    nfs-server:
      ansible_host: 192.168.153.129
      ansible_port: 2214
    k8s-server-01:
      ansible_host: 192.168.153.129
      ansible_port: 2215
    k8s-server-02:
      ansible_host: 192.168.153.129
      ansible_port: 2216
    k8s-server-03:
      ansible_host: 192.168.153.129
      ansible_port: 2217
    k8s-worker-01:
      ansible_host: 192.168.153.129
      ansible_port: 2218
    k8s-worker-02:
      ansible_host: 192.168.153.129
      ansible_port: 2219
    k8s-worker-03:
      ansible_host: 192.168.153.129
      ansible_port: 2220
  children:
    k8s_servers:
      hosts:
        k8s-server-01:
        k8s-server-02:
        k8s-server-03:
    k8s_workers:
      hosts:
        k8s-worker-01:
        k8s-worker-02:
        k8s-worker-03:
