---
all:
  hosts:
    mgmt_server:
      ansible_host: 192.168.44.22
      ansible_port: 22
    server2:
      ansible_host: 192.168.1.102
    switch1:
      ansible_host: 192.168.1.106
    switch2:
      ansible_host: 192.168.1.107
  children:
    mgmt_servers:
      hosts:
        mgmt_server:
